'use client';

import type { FinalReport, ScoreDimension } from '@/lib/interview/types';
import { Button } from '@/components/ui/button';

const LABELS: Record<ScoreDimension, string> = {
  knowledge: 'Knowledge',
  reasoning: 'Reasoning',
  relevance: 'Relevance',
  communication: 'Communication',
  vocabulary: 'Vocabulary',
  confidence: 'Confidence & delivery',
};

type AssessmentReportProps = {
  report: FinalReport;
  onStartOver: () => void;
};

function formatTime(timestampMs: number) {
  return new Intl.DateTimeFormat(undefined, {
    hour: 'numeric',
    minute: '2-digit',
    second: '2-digit',
  }).format(new Date(timestampMs));
}

export function AssessmentReport({ report, onStartOver }: AssessmentReportProps) {
  return (
    <div className="mx-auto max-h-[min(90dvh,52rem)] w-[min(92vw,42rem)] overflow-y-auto rounded-[20px] border border-[#2b2b2b] bg-[#101010] px-6 py-8 text-left shadow-[0_10px_24px_rgba(0,0,0,0.28)]">
      <p className="text-xs font-medium uppercase tracking-wide text-amber-200">
        AI disclosure — this assessment was generated by EchoSphere, not a human interviewer.
      </p>
      <h1 className="mt-3 text-2xl font-medium text-white">Interview report</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Overall score{' '}
        <span className="text-lg font-semibold text-white">{report.overallScore}/100</span>
      </p>

      <section className="mt-6">
        <h2 className="text-sm font-semibold text-white">Dimension breakdown</h2>
        <ul className="mt-2 space-y-1.5 text-sm text-muted-foreground">
          {(Object.keys(LABELS) as ScoreDimension[]).map((key) => (
            <li key={key} className="flex justify-between gap-4">
              <span>{LABELS[key]}</span>
              <span className="text-white">{report.dimensions[key]}</span>
            </li>
          ))}
        </ul>
      </section>

      {report.strengths.length > 0 && (
        <section className="mt-6">
          <h2 className="text-sm font-semibold text-white">Strengths</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
            {report.strengths.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      {report.weaknesses.length > 0 && (
        <section className="mt-6">
          <h2 className="text-sm font-semibold text-white">Gaps</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
            {report.weaknesses.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      {report.contradictions.length > 0 && (
        <section className="mt-6">
          <h2 className="text-sm font-semibold text-white">Contradictions / red flags</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
            {report.contradictions.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      {report.evidence.length > 0 && (
        <section className="mt-6">
          <h2 className="text-sm font-semibold text-white">Evidence from transcript</h2>
          <ul className="mt-2 space-y-3 text-sm">
            {report.evidence.slice(0, 8).map((item, index) => (
              <li
                key={`${item.turnId}-${item.dimension}-${index}`}
                className="rounded-lg border border-border px-3 py-2"
              >
                <p className="text-xs text-muted-foreground">
                  {LABELS[item.dimension]} · {item.score}/100
                  {item.timestampMs ? ` · ${formatTime(item.timestampMs)}` : ''}
                </p>
                <p className="mt-1 text-white">&ldquo;{item.quote}&rdquo;</p>
                <p className="mt-1 text-muted-foreground">{item.evidence}</p>
              </li>
            ))}
          </ul>
        </section>
      )}

      {report.recommendations.length > 0 && (
        <section className="mt-6">
          <h2 className="text-sm font-semibold text-white">What to practice next</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
            {report.recommendations.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      <Button
        onClick={onStartOver}
        className="mt-8 h-10 w-full rounded-lg border border-primary bg-primary text-sm font-medium text-black hover:border-white hover:bg-white"
      >
        Start another interview
      </Button>
    </div>
  );
}
